import { StatusBadge } from "@/components/feedback/StatusBadge";
import type { AuditRecord } from "@/core/types/models/audit";

import { formatFindingTimeline } from "./finding-timeline";

export function AuditFindingsCard({ audit }: { audit: AuditRecord }) {
  return <div className="rounded-lg border p-3"><div className="flex items-center justify-between gap-3"><div className="text-sm font-medium">Findings</div><div className="flex flex-wrap justify-end gap-2"><StatusBadge tone="neutral">Minor {audit.findingsCount.minor}</StatusBadge><StatusBadge tone="warning">Major {audit.findingsCount.major}</StatusBadge><StatusBadge tone="critical">Critical {audit.findingsCount.critical}</StatusBadge></div></div><div className="mt-3 space-y-2">{audit.findings.slice(0, 8).map((finding) => { const person = finding.responsiblePerson ?? finding.owner; const timeline = formatFindingTimeline(finding); return <div key={finding.id} className="rounded-md border p-2"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-medium">{finding.title}</div>{finding.description ? <div className="text-muted-foreground mt-1 line-clamp-2 text-xs">{finding.description}</div> : null}<div className="text-muted-foreground mt-1 text-xs">{finding.area} ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ {finding.status}{person ? ` ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ ${person}` : ""}{finding.responsibleTeam ? ` ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ ${finding.responsibleTeam}` : ""}{timeline ? ` ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ ${timeline}` : ""}</div>{finding.action ? <div className="text-muted-foreground mt-1 text-xs">Action: {finding.action}</div> : null}</div><StatusBadge tone={finding.severity === "critical" ? "critical" : finding.severity === "major" ? "warning" : "neutral"}>{finding.severity}</StatusBadge></div></div>; })}{!audit.findings.length ? <div className="text-muted-foreground text-sm">No findings recorded.</div> : null}</div></div>;
}

