import type { CompanyOption } from "@/core/app/state/slices/company";
import type { UtilityUsageStatus } from "@/features/operations/utilities/config/baseline-settings";
import type { UtilityMeterOption, UtilitySourceOption, UtilityType, UtilityUomOption } from "@/core/types/models/ems";

export type UtilityFormProps = {
  showValidation?: boolean;
  companies: CompanyOption[];
  companyId: string;
  type: UtilityType;
  onTypeChange: (value: UtilityType) => void;
  meterId: string;
  onMeterIdChange: (value: string) => void;
  meterOptions: UtilityMeterOption[];
  unit: string;
  onUnitChange: (value: string) => void;
  uomOptions: UtilityUomOption[];
  sourceId: string;
  onSourceChange: (value: string) => void;
  sourceOptions: UtilitySourceOption[];
  periodStart: string;
  onPeriodStartChange: (value: string) => void;
  periodEnd: string;
  onPeriodEndChange: (value: string) => void;
  meterName: string;
  onMeterNameChange: (value: string) => void;
  previousReading: string;
  onPreviousReadingChange: (value: string) => void;
  currentReading: string;
  onCurrentReadingChange: (value: string) => void;
  consumptionInput: string;
  onConsumptionInputChange: (value: string) => void;
  dieselLitersInput: string;
  onDieselLitersInputChange: (value: string) => void;
  consumption?: number;
  status?: UtilityUsageStatus;
  coverageWarning?: string;
  remarks: string;
  onRemarksChange: (value: string) => void;
  attachment: File | null;
  attachmentError?: string;
  onAttachmentChange: (file: File | null) => void;
};

export type UtilityFormErrors = {
  company: string;
  type: string;
  unit: string;
  source: string;
  periodStart: string;
  periodEnd: string;
  coverage: string;
  meterName: string;
  previousReading: string;
  currentReading: string;
  consumption: string;
};
