import { Pause, Play } from "lucide-react";

import { cn } from "@/app/components/ui/utils";

import { formatTime } from "./voice-message/format-time";
import type { VoiceMessageProps } from "./voice-message/types";
import { useVoiceMessage } from "./voice-message/use-voice-message";

export function VoiceMessage({ src, durationSec, className, density = "default", variant = "default", labels }: VoiceMessageProps) {
  const message = useVoiceMessage(durationSec);
  return <div className={cn("flex items-center gap-2", density === "compact" ? "gap-2" : "gap-3", className)}><audio ref={message.audioRef} src={src} preload="metadata" /><button type="button" onClick={message.toggle} className={cn("grid place-items-center rounded-full border bg-background/40 hover:bg-background/60", density === "compact" ? "size-8" : "size-9")} aria-label={message.playing ? labels?.pause || "Pause" : labels?.play || "Play"}>{message.playing ? <Pause className="size-4" /> : <Play className="ml-0.5 size-4" />}</button><div role="slider" aria-label="Seek" aria-valuemin={0} aria-valuemax={message.total || 0} aria-valuenow={message.current} tabIndex={0} className={cn("relative h-2 flex-1 cursor-pointer rounded-full bg-muted", "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50")} onPointerDown={(event) => { const audio = message.audioRef.current; if (!audio || message.total <= 0) return; message.seekingRef.current = true; (event.currentTarget as HTMLDivElement).setPointerCapture?.(event.pointerId); message.onSeek(event.clientX, event.currentTarget.getBoundingClientRect()); }} onPointerMove={(event) => { if (!message.seekingRef.current) return; message.onSeek(event.clientX, (event.currentTarget as HTMLDivElement).getBoundingClientRect()); }} onPointerUp={() => { message.seekingRef.current = false; }} onPointerCancel={() => { message.seekingRef.current = false; }} onKeyDown={(event) => { const audio = message.audioRef.current; if (!audio || message.total <= 0) return; if (event.key === "ArrowLeft") { event.preventDefault(); audio.currentTime = Math.max(0, (audio.currentTime || 0) - 5); message.setCurrent(audio.currentTime); } if (event.key === "ArrowRight") { event.preventDefault(); audio.currentTime = Math.min(message.total, (audio.currentTime || 0) + 5); message.setCurrent(audio.currentTime); } }}><span className="absolute inset-y-0 left-0 rounded-full bg-primary/60" style={{ width: `${message.pct * 100}%` }} /><span className="absolute top-1/2 -translate-y-1/2 rounded-full bg-primary shadow-sm" style={{ left: `calc(${message.pct * 100}% - 6px)`, width: 12, height: 12 }} /></div><div className="text-muted-foreground shrink-0 text-xs tabular-nums">{variant === "whatsapp" && message.total > 0 ? `-${formatTime(message.remaining)}` : message.total > 0 ? formatTime(message.total) : formatTime(durationSec || 0)}</div></div>;
}
