import { Camera, Mic, Send, Trash2, X } from "lucide-react";

import { Button } from "@/components/ui/primitives/button";
import { Textarea } from "@/components/ui/primitives/textarea";
import { cn } from "@/components/ui/primitives/utils";
import { BN } from "@/features/public/report-box/text";

export function ComposerBar(props: any) {
  return (
    <div className="bg-background/90 supports-[backdrop-filter]:bg-background/75 sticky bottom-0 z-40 border-t backdrop-blur">
      {props.state.editTarget ? <div className="px-3 pt-2"><div className="rounded-xl border bg-card px-3 py-2 text-xs"><div className="flex items-center justify-between gap-2"><div className="text-muted-foreground truncate">{BN.edit}</div><Button variant="ghost" size="sm" className="h-7 px-2" onClick={() => { props.state.setEditTarget(null); props.state.setComposer(""); }} disabled={props.state.sending}><X className="mr-2 size-4" />{BN.cancel}</Button></div></div></div> : null}
      <div className="flex items-end gap-2 px-3 py-3">
        <input ref={props.refs.fileRef} type="file" accept="image/*" className="hidden" onChange={(e) => props.actions.onPickPhoto(e.target.files?.[0] ?? null)} />
        <Button variant="outline" size="icon" aria-label={BN.attachPhoto} onClick={() => props.refs.fileRef.current?.click()} disabled={!props.companyValid || props.state.locked || props.state.sending || props.remaining <= 0 || props.state.recording || props.state.voicePanelOpen}><Camera className="size-4" /></Button>
        <div className="flex-1">{props.state.voicePanelOpen ? <VoicePanel {...props} /> : <Textarea ref={(node) => { props.refs.composerRef.current = node; }} value={props.state.composer} onChange={(e) => props.state.setComposer(e.target.value)} placeholder={BN.typeMsg} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); props.actions.sendText(); } }} disabled={!props.companyValid || props.state.locked || props.state.sending || props.remaining <= 0 || props.state.recording} className="min-h-11" />}</div>
        {props.state.composer.trim().length > 0 || props.state.editTarget ? <Button size="icon" aria-label={BN.send} onClick={props.actions.sendText} disabled={!props.companyValid || props.state.locked || props.state.sending || props.remaining <= 0 || props.state.recording || !props.state.composer.trim()}><Send className="size-4" /></Button> : <MicButton {...props} />}
      </div>
    </div>
  );
}

function VoicePanel(props: any) {
  return <div className="rounded-xl border bg-card px-3 py-2"><div className="flex items-center justify-between gap-2"><Button variant="ghost" size="icon" className="h-9 w-9" aria-label={BN.delete} onClick={() => { if (props.state.recording) { props.setCancelArmedSync(true); props.refs.closeVoicePanelAfterStopRef.current = true; props.voice.stopVoice(); return; } props.state.setVoicePanelOpen(false); }} disabled={props.state.sending}><Trash2 className="size-4" /></Button><div className="flex flex-col items-center"><div className="mb-1 flex items-center gap-1 text-xs"><span className={cn("inline-block h-1.5 w-1.5 rounded-full", props.state.recording ? "bg-destructive animate-pulse" : "bg-muted-foreground/40")} /><span className={cn("font-mono", props.state.recording ? "text-foreground" : "text-muted-foreground")}>{props.formatClock(props.state.recordingSeconds)}</span></div><Button variant={props.state.recording ? "destructive" : "outline"} size="icon" className={cn("h-10 w-10 rounded-full", props.state.recording ? "shadow-[0_0_0_6px_rgba(239,68,68,0.10)]" : "")} aria-label={props.state.recording ? BN.stop : BN.holdRecord} onPointerDown={() => { props.refs.closeVoicePanelAfterStopRef.current = true; if (!props.state.recording) void props.voice.startVoice(); }} onPointerUp={() => { props.refs.closeVoicePanelAfterStopRef.current = true; props.voice.stopVoice(); }} onPointerCancel={() => { props.refs.closeVoicePanelAfterStopRef.current = true; props.voice.stopVoice(); }} disabled={!props.companyValid || props.state.locked || props.state.sending || props.remaining <= 0}><Mic className="size-4" /></Button></div><Button variant="ghost" size="icon" className={cn("h-9 w-9", props.state.recording ? "text-[var(--success-700)]" : "text-muted-foreground")} aria-label={BN.send} onClick={() => { props.refs.closeVoicePanelAfterStopRef.current = true; props.voice.stopVoice(); }} disabled={!props.state.recording || props.state.sending}><Send className="size-4" /></Button></div></div>;
}

function MicButton(props: any) {
  return <Button variant={props.state.recording ? "destructive" : "outline"} size="icon" aria-label={props.state.recording ? BN.stop : BN.holdRecord} onClick={() => { if (props.refs.ignoreNextClickRef.current) return void (props.refs.ignoreNextClickRef.current = false); props.refs.autoStopOnReleaseRef.current = false; props.refs.closeVoicePanelAfterStopRef.current = true; props.state.setVoicePanelOpen(true); if (!props.state.recording) void props.voice.startVoice(); }} onTouchStart={(e) => { e.preventDefault(); props.refs.ignoreNextClickRef.current = true; if (props.state.recording) return; props.refs.touchStartAtRef.current = Date.now(); props.refs.autoStopOnReleaseRef.current = true; props.refs.closeVoicePanelAfterStopRef.current = true; props.state.setVoicePanelOpen(true); void props.voice.startVoice(); }} onTouchEnd={(e) => { e.preventDefault(); if (!props.refs.autoStopOnReleaseRef.current) return; const heldMs = props.refs.touchStartAtRef.current ? Date.now() - props.refs.touchStartAtRef.current : 0; props.refs.touchStartAtRef.current = null; if (heldMs > 0 && heldMs < 220) return void (props.refs.autoStopOnReleaseRef.current = false); props.voice.stopVoice(); props.refs.autoStopOnReleaseRef.current = false; }} disabled={!props.companyValid || props.state.locked || props.state.sending || props.remaining <= 0}><Mic className="size-4" /></Button>;
}

