export const permissionCatalog = [
  ["Audit calendar", "audit-calendar:read", "Read"], ["Audit calendar", "audit-calendar:write", "Write"], ["Audit calendar", "audit-calendar:update", "Update"], ["Audit calendar", "audit-calendar:delete", "Delete"],
  ["Companies", "companies:read", "Read"], ["Utilities", "utilities:read", "Read"], ["Utilities", "utilities:write", "Write"], ["Utilities", "utilities:update", "Update"], ["Utilities", "utilities:delete", "Delete"],
  ["Chemicals", "chemicals:read", "Read"], ["Chemicals", "chemicals:write", "Write"], ["Chemicals", "chemicals:update", "Update"], ["Chemicals", "chemicals:delete", "Delete"],
  ["SDS / MSDS", "sds:read", "Read"], ["SDS / MSDS", "sds:write", "Write"], ["SDS / MSDS", "sds:update", "Update"], ["SDS / MSDS", "sds:delete", "Delete"],
  ["Waste", "waste:read", "Read"], ["Waste", "waste:write", "Write"], ["Waste", "waste:update", "Update"], ["Waste", "waste:delete", "Delete"],
  ["Wastewater / ETP", "wastewater:read", "Read"], ["Wastewater / ETP", "wastewater:write", "Write"], ["Wastewater / ETP", "wastewater:update", "Update"], ["Wastewater / ETP", "wastewater:delete", "Delete"],
  ["Audits", "audits:read", "Read"], ["Audits", "audits:write", "Write"], ["Audits", "audits:update", "Update"], ["Audits", "audits:delete", "Delete"],
  ["CAPA", "capa:read", "Read"], ["CAPA", "capa:write", "Write"], ["CAPA", "capa:update", "Update"], ["CAPA", "capa:delete", "Delete"],
  ["Reports", "reports:read", "Read"], ["Reports", "reports:export", "Export"], ["Documents", "documents:read", "Read"], ["Documents", "documents:write", "Write"], ["Documents", "documents:update", "Update"], ["Documents", "documents:delete", "Delete"],
  ["Incidents", "incidents:read", "Read"], ["Incidents", "incidents:write", "Write"], ["Incidents", "incidents:update", "Update"], ["Incidents", "incidents:delete", "Delete"],
  ["Training", "training:read", "Read"], ["Training", "training:write", "Write"], ["Training", "training:update", "Update"], ["Training", "training:delete", "Delete"],
  ["Notifications", "notifications:read", "Read"], ["Notifications", "notifications:write", "Write"], ["Notifications", "notifications:update", "Update"], ["Notifications", "notifications:delete", "Delete"],
  ["Settings", "settings:read", "Read"], ["Settings", "settings:manage", "Manage all"],
  ["Settings - Employees", "settings:employees:read", "Read"], ["Settings - Employees", "settings:employees:write", "Write"], ["Settings - Employees", "settings:employees:update", "Update"], ["Settings - Employees", "settings:employees:delete", "Delete"],
  ["Settings - Users", "settings:users:read", "Read"], ["Settings - Users", "settings:users:write", "Write"], ["Settings - Users", "settings:users:update", "Update"], ["Settings - Users", "settings:users:delete", "Delete"],
  ["Settings - Roles", "settings:roles:read", "Read"], ["Settings - Roles", "settings:roles:write", "Write"], ["Settings - Roles", "settings:roles:update", "Update"], ["Settings - Roles", "settings:roles:delete", "Delete"],
  ["Settings - Departments", "settings:departments:read", "Read"], ["Settings - Departments", "settings:departments:write", "Write"], ["Settings - Departments", "settings:departments:update", "Update"], ["Settings - Departments", "settings:departments:delete", "Delete"],
  ["Settings - Designations", "settings:designations:read", "Read"], ["Settings - Designations", "settings:designations:write", "Write"], ["Settings - Designations", "settings:designations:update", "Update"], ["Settings - Designations", "settings:designations:delete", "Delete"],
  ["Settings - Companies", "settings:companies:read", "Read"], ["Settings - Companies", "settings:companies:write", "Write"], ["Settings - Companies", "settings:companies:update", "Update"], ["Settings - Companies", "settings:companies:delete", "Delete"],
  ["Settings - UOM", "settings:uom:read", "Read"], ["Settings - UOM", "settings:uom:write", "Write"], ["Settings - UOM", "settings:uom:update", "Update"], ["Settings - UOM", "settings:uom:delete", "Delete"],
  ["Settings - UOM Wiring", "settings:uom-wiring:read", "Read"], ["Settings - UOM Wiring", "settings:uom-wiring:write", "Write"], ["Settings - UOM Wiring", "settings:uom-wiring:update", "Update"], ["Settings - UOM Wiring", "settings:uom-wiring:delete", "Delete"],
  ["Settings - Sources", "settings:sources:read", "Read"], ["Settings - Sources", "settings:sources:write", "Write"], ["Settings - Sources", "settings:sources:update", "Update"], ["Settings - Sources", "settings:sources:delete", "Delete"],
  ["Settings - Source Wiring", "settings:source-wiring:read", "Read"], ["Settings - Source Wiring", "settings:source-wiring:write", "Write"], ["Settings - Source Wiring", "settings:source-wiring:update", "Update"], ["Settings - Source Wiring", "settings:source-wiring:delete", "Delete"],
  ["Settings - Suppliers", "settings:suppliers:read", "Read"], ["Settings - Suppliers", "settings:suppliers:write", "Write"], ["Settings - Suppliers", "settings:suppliers:update", "Update"], ["Settings - Suppliers", "settings:suppliers:delete", "Delete"],
];

export const permissionOptions = permissionCatalog.map(([group, key, action], index) => ({
  key,
  group,
  action,
  label: `${group} - ${action}`,
  order: index,
}));
